"""Render the coverage matrix table (for docs/api-coverage.md) and the shields.io
endpoint badge JSON (docs/coverage-badge.json) from the canonical registry. Run:

    python tools/render_coverage.py        # writes both files

The drift test (tests/test_coverage_doc_in_sync.py) asserts the committed files
match this renderer, so the doc/badge can never silently rot.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from tests.e2e.endpoints import COVERAGE, ENDPOINTS  # noqa: E402

DOC = REPO / "docs" / "api-coverage.md"
BADGE = REPO / "docs" / "coverage-badge.json"

MARKER = "<!-- COVERAGE-MATRIX (generated by tools/render_coverage.py — do not edit below) -->"


def _cell(node: str | None, applicable: bool) -> str:
    if not applicable:
        return "N/A"
    return "tested" if node else "untested"


def render() -> tuple[str, str]:
    rows = ["| Endpoint | HTTP / WS | CLI + | CLI − | SDK + | SDK − |",
            "|----------|-----------|:-----:|:-----:|:-----:|:-----:|"]
    tested = applicable = 0
    for e in ENDPOINTS:
        c = COVERAGE[e.id]
        sdk_on = e.sdk is not None
        cli_pos = _cell(c.cli_pos, True)
        cli_neg = _cell(c.cli_neg, True)
        sdk_pos = _cell(c.sdk_pos, sdk_on)
        sdk_neg = _cell(c.sdk_neg, sdk_on)
        for cell in (cli_pos, cli_neg, sdk_pos, sdk_neg):
            if cell == "N/A":
                continue
            applicable += 1
            if cell == "tested":
                tested += 1
        rows.append(f"| `{e.id}` | `{e.http}` | {cli_pos} | {cli_neg} | {sdk_pos} | {sdk_neg} |")
    pct = round(100 * tested / applicable) if applicable else 0
    na_total = sum(1 for e in ENDPOINTS if e.sdk is None) * 2
    na_note = (" N/A = operation not exposed on that surface "
               "(CLI-only connectivity primitives)." if na_total else "")
    summary = (f"\n**Coverage: {tested}/{applicable} applicable cells tested "
               f"({pct}%) across {len(ENDPOINTS)} endpoints"
               f" — CLI and SDK, positive and negative.**{na_note}\n")
    table_md = MARKER + "\n\n## Test matrix\n\n" + "\n".join(rows) + "\n" + summary

    color = "brightgreen" if pct == 100 else ("yellow" if pct >= 80 else "red")
    badge = {"schemaVersion": 1, "label": "CLI + SDK coverage",
             "message": f"{tested}/{applicable} ({pct}%)", "color": color}
    return table_md, json.dumps(badge, indent=2) + "\n"


def main() -> None:
    table_md, badge_json = render()
    # Pin UTF-8: the matrix uses non-ASCII chars (— and the − column headers);
    # without this, Windows defaults to cp1252 and mangles them (drift mismatch).
    text = DOC.read_text(encoding="utf-8")
    head = text.split(MARKER)[0].rstrip() + "\n\n"
    DOC.write_text(head + table_md, encoding="utf-8")
    BADGE.write_text(badge_json, encoding="utf-8")
    print(f"wrote {DOC} and {BADGE}")


if __name__ == "__main__":
    main()
